name: FreeRDP

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'Unique run identifier'
        required: false
        type: string
        default: 'default'

jobs:
  secure-rdp:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Track Run ID
        shell: powershell
        run: |
          # Step name will be used to match ID in polling
          $runId = "${{ github.event.inputs.run_id }}"
          Write-Host "Unique Run ID: $runId"
          echo "TRACK_RUN_ID=$runId" >> $env:GITHUB_ENV

      - name: Configure Core RDP Settings
        shell: powershell
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "SecurityLayer" -Value 0 -Force
          netsh advfirewall firewall delete rule name="FreeRDP-Tailscale" 2>$null
          netsh advfirewall firewall add rule name="FreeRDP-Tailscale" dir=in action=allow protocol=TCP localport=3389
          Restart-Service -Name TermService -Force
          Write-Host "RDP configured."

      - name: Create RDP User with Secure Password
        shell: powershell
        run: |
          Add-Type -AssemblyName System.Security
          $charSet = @{
              Upper = [char[]](65..90)
              Lower = [char[]](97..122)
              Number = [char[]](48..57)
              Special = ([char[]](33..47) + [char[]](58..64) + [char[]](91..96) + [char[]](123..126))
          }
          $rawPassword = @()
          $rawPassword += $charSet.Upper | Get-Random -Count 4
          $rawPassword += $charSet.Lower | Get-Random -Count 4
          $rawPassword += $charSet.Number | Get-Random -Count 4
          $rawPassword += $charSet.Special | Get-Random -Count 4
          $password = -join ($rawPassword | Sort-Object { Get-Random })
          $securePass = ConvertTo-SecureString $password -AsPlainText -Force
          New-LocalUser -Name "RDP" -Password $securePass -AccountNeverExpires
          Add-LocalGroupMember -Group "Administrators" -Member "RDP"
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member "RDP"
          echo "RDP_PASSWORD=$password" >> $env:GITHUB_ENV
          Write-Host "=== FreeRDP CREDENTIALS ==="
          Write-Host "Username: RDP"
          Write-Host "Password: $password"
          Write-Host "=========================="

      - name: Install Tailscale
        shell: powershell
        run: |
          $tsUrl = "https://pkgs.tailscale.com/stable/tailscale.msi"
          $installerPath = "$env:TEMP\tailscale.msi"
          Invoke-WebRequest -Uri $tsUrl -OutFile $installerPath
          Start-Process msiexec.exe -ArgumentList "/i `"$installerPath`" /quiet /norestart" -Wait
          Remove-Item $installerPath -Force

      - name: Establish Tailscale Connection
        shell: powershell
        run: |
          $tailscalePath = "$env:ProgramFiles\Tailscale\tailscale.exe"
          & $tailscalePath up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=free-rdp-${{ github.run_id }} --accept-routes
          $tsIP = $null
          $retries = 0
          while (-not $tsIP -and $retries -lt 20) {
              Start-Sleep -Seconds 3
              $ipOutput = & $tailscalePath ip --4 2>$null
              if ($ipOutput) { $tsIP = $ipOutput.Trim() }
              $retries++
          }
          if (-not $tsIP) { Write-Error "Tailscale IP failed"; exit 1 }
          echo "TAILSCALE_IP=$tsIP" >> $env:GITHUB_ENV
          Write-Host "Tailscale IP: $tsIP"

      - name: Verify RDP Accessibility
        shell: powershell
        run: |
          $test = Test-NetConnection -ComputerName $env:TAILSCALE_IP -Port 3389 -WarningAction SilentlyContinue
          if (-not $test.TcpTestSucceeded) { Write-Error "RDP port failed"; exit 1 }
          Write-Host "RDP verified on $env:TAILSCALE_IP:3389"

      - name: Maintain Connection
        shell: powershell
        run: |
          $endTime = (Get-Date).AddMinutes(350)
          while ((Get-Date) -lt $endTime) {
              Write-Host "[$(Get-Date)] Active - IP: $env:TAILSCALE_IP | User: RDP | Pass: $env:RDP_PASSWORD"
              Start-Sleep -Seconds 300
          }
