name: RDP

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'Unique run identifier'
        required: false
        type: string
        default: 'default'

jobs:
  secure-rdp:
    runs-on: windows-latest
    timeout-minutes: 3600

    steps:
      - name: Track Run ID
        shell: powershell
        run: |
          $runId = "${{ github.event.inputs.run_id || 'default' }}"
          Write-Host "TRACK_ID: $runId"  # For parsing match

      - name: Configure Core RDP Settings
        shell: powershell
        run: |
          # Enable Remote Desktop and disable NLA
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 0 -Force
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "SecurityLayer" -Value 0 -Force

          # Firewall rule
          netsh advfirewall firewall delete rule name="RDP-Tailscale" 2>$null
          netsh advfirewall firewall add rule name="RDP-Tailscale" dir=in action=allow protocol=TCP localport=3389

          # Restart service
          Restart-Service -Name TermService -Force
          Write-Host "RDP configured."

      - name: Create RDP User with Secure Password
        shell: powershell
        run: |
          Add-Type -AssemblyName System.Security
          $charSet = @{
              Upper = [char[]](65..90)  # A-Z
              Lower = [char[]](97..122) # a-z
              Number = [char[]](48..57) # 0-9
              Special = ([char[]](33..47) + [char[]](58..64) + [char[]](91..96) + [char[]](123..126)) # Special
          }
          $rawPassword = @()
          $rawPassword += $charSet.Upper | Get-Random -Count 4
          $rawPassword += $charSet.Lower | Get-Random -Count 4
          $rawPassword += $charSet.Number | Get-Random -Count 4
          $rawPassword += $charSet.Special | Get-Random -Count 4
          $password = -join ($rawPassword | Sort-Object { Get-Random })
          $securePass = ConvertTo-SecureString $password -AsPlainText -Force
          New-LocalUser -Name "RDP" -Password $securePass -AccountNeverExpires
          Add-LocalGroupMember -Group "Administrators" -Member "RDP"
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member "RDP"
          
          if (-not (Get-LocalUser -Name "RDP")) {
              Write-Error "User creation failed"
              exit 1
          }
          
          # Echo for parsing
          Write-Host "PASS: $password"  # Clear format for regex

      - name: Install Tailscale with Retry
        shell: powershell
        run: |
          $tsUrl = "https://pkgs.tailscale.com/stable/tailscale-setup-1.82.0-amd64.msi"  # Your working specific version
          $installerPath = "$env:TEMP\tailscale.msi"
          
          # Flush DNS
          ipconfig /flushdns 2>$null
          
          $maxRetries = 3
          $retry = 0
          $success = $false
          while ($retry -lt $maxRetries -and -not $success) {
              try {
                  Write-Host "Download attempt $($retry + 1)/$maxRetries"
                  Invoke-WebRequest -Uri $tsUrl -OutFile "`"$installerPath`"" -TimeoutSec 90 -ErrorAction Stop
                  $success = $true
                  Write-Host "Download succeeded!"
              } catch {
                  Write-Host "Download failed: $($_.Exception.Message)"
                  Remove-Item $installerPath -Force -ErrorAction SilentlyContinue
                  $retry++
                  if ($retry -lt $maxRetries) {
                      Start-Sleep -Seconds 10
                      ipconfig /flushdns 2>$null
                  }
              }
          }
          if (-not $success) {
              Write-Error "Download failed after retries"
              exit 1
          }
          
          Start-Process msiexec.exe -ArgumentList "/i", "`"$installerPath`"", "/quiet", "/norestart" -Wait
          Remove-Item $installerPath -Force

      - name: Establish Tailscale Connection
        shell: powershell
        run: |
          # Up Tailscale
          & "$env:ProgramFiles\Tailscale\tailscale.exe" up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-runner-${{ github.run_id }} --accept-routes --accept-dns=false
          
          # Wait IP with retry
          $tsIP = $null
          $retries = 0
          while (-not $tsIP -and $retries -lt 20) {  # More retries
              Start-Sleep -Seconds 5
              $ipOutput = & "$env:ProgramFiles\Tailscale\tailscale.exe" ip -4 2>$null
              if ($ipOutput -and $ipOutput.Trim()) {
                  $tsIP = $ipOutput.Trim()
                  Write-Host "IP: $tsIP"  # Clear format for parsing
              }
              $retries++
          }
          
          if (-not $tsIP) {
              Write-Error "Tailscale IP not assigned"
              exit 1
          }

      - name: Verify RDP Accessibility
        shell: powershell
        run: |
          $testResult = Test-NetConnection -ComputerName $env:TAILSCALE_IP -Port 3389
          if (-not $testResult.TcpTestSucceeded) {
              Write-Error "RDP port failed"
              exit 1
          }
          Write-Host "RDP verified."

      - name: Maintain Connection
        shell: powershell
        run: |
          Write-Host "`n=== RDP READY ==="
          Write-Host "IP: $env:TAILSCALE_IP"
          Write-Host "USER: RDP"
          Write-Host "PASS: $env:RDP_PASSWORD"  # Fallback if not echoed
          Write-Host "================`n"
          
          # Loop active
          while ($true) {
              Write-Host "[$(Get-Date)] Active - Connect via Tailscale to IP: $env:TAILSCALE_IP"
              Start-Sleep -Seconds 300
          }
